"""This the same as algo1 but using deduplication after each recursive step. Also taken from alo2,
we will change the way we find and use beta and stop the whole process.
Another change is that we will create combine the keys of blocks that have the same reference IDs. 
This is to reduce the number of blocks and increase the size of blocks. """


import build_tokenFreqDict
from refine_blocks import refine_blocks
import ast
from pathlib import Path
import build_refDict

def load_dict(path_str):
    path = Path(path_str)
    with open(path, "r", encoding="utf-8") as f:
        return ast.literal_eval(f.read())

from statistics import mean
from scipy.stats import mode
from math import floor
import time

def compute_stop_k(refDict):
    token_lengths = [len(set(tokens)) for tokens in refDict.values()]
    mode_length = mode(token_lengths, keepdims=True)[0][0]
    stop_k = floor(0.6 * mode_length)
    print("Mode token length:", mode_length)
    print("Stopping threshold k:", stop_k)
    return stop_k

def recursive_blocking(beta, blocks, stop_k):
    print(f"\n--- Beta = {beta}, Stop_k = {stop_k} ---")
    print(f"Current number of blocks: {len(blocks)}")
    
    if beta > stop_k:
        print("Stopping: beta > stop_k")
        return blocks
    
    print(f"Calling refine_blocks with beta={beta}...")
    start_time = time.time()
    newBlocks = refine_blocks(blocks, beta)
    refine_time = time.time() - start_time
    print(f"refine_blocks took {refine_time:.2f} seconds, produced {len(newBlocks) if newBlocks else 0} blocks")
    
    if not newBlocks:
        print("Stopping: newBlocks is empty")
        return blocks
    
    print(f"Merging blocks...")
    start_time = time.time()
    merged_blocks = merge_blocks(blocks, newBlocks)
    merge_time = time.time() - start_time
    print(f"merge_blocks took {merge_time:.2f} seconds, result: {len(merged_blocks)} blocks")

    print(f"Purging subset blocks...")
    start_time = time.time()
    before = len(merged_blocks)
    merged_blocks = purge_subset_blocks(merged_blocks)
    purge_time = time.time() - start_time
    print(f"purge_subset_blocks took {purge_time:.2f} seconds, "
          f"dropped {before - len(merged_blocks)}, result: {len(merged_blocks)} blocks")

    return recursive_blocking(beta + 1, merged_blocks, stop_k)

def merge_blocks(old_blocks, new_blocks):
    """Optimized merge using a single pass with hash-based deduplication"""
    ref_set_to_data = {}  # Maps frozenset of refs -> (list of keys, refs dict)
    
    # Combine both dictionaries
    combined = {**old_blocks, **new_blocks}
    
    # Single pass: group by reference set
    for key, refs in combined.items():
        ref_set = frozenset(refs.keys())
        
        # Normalize key to ensure it's hashable
        if isinstance(key, tuple):
            key_tuple = key
        else:
            key_tuple = (key,)
        
        if ref_set not in ref_set_to_data:
            # First occurrence of this reference set
            ref_set_to_data[ref_set] = (list(key_tuple), refs)
        else:
            # Add new keys to existing list (will dedupe later)
            existing_keys, _ = ref_set_to_data[ref_set]
            existing_keys.extend(key_tuple)
    
    # Build final merged dictionary
    merged = {}
    for ref_set, (key_list, refs) in ref_set_to_data.items():
        # Deduplicate keys using set (fast) then convert back to list
        unique_keys = list(dict.fromkeys(key_list))  # Preserves order, removes dupes
        
        # Create final key
        if len(unique_keys) == 1:
            final_key = unique_keys[0]
        else:
            final_key = tuple(unique_keys)
        
        merged[final_key] = refs
    
    return merged

def purge_subset_blocks(blocks):
    """Lossless subset purging: drop block B if its reference set is a strict
    subset of some other block A's reference set. Every pair generated by B is
    then still generated by A, so no candidate pairs are lost.

    Uses an inverted refID -> set(block_keys) index. For each block, the
    intersection of indexes over its refIDs gives all blocks that contain ALL
    of its refs (i.e. supersets, including itself). If any other block remains,
    the current block is redundant.
    """
    from collections import defaultdict

    block_keys = list(blocks.keys())
    block_id = {k: i for i, k in enumerate(block_keys)}
    block_size = [len(blocks[k]) for k in block_keys]

    ref_to_blocks = defaultdict(set)
    for i, k in enumerate(block_keys):
        for refID in blocks[k]:
            ref_to_blocks[refID].add(i)

    keep = {}
    for i, k in enumerate(block_keys):
        refs = blocks[k]
        if not refs:
            continue
        ref_iter = iter(refs)
        first = next(ref_iter)
        candidates = set(ref_to_blocks[first])
        for refID in ref_iter:
            candidates &= ref_to_blocks[refID]
            if len(candidates) == 1:
                break

        is_strict_subset = False
        for j in candidates:
            if j == i:
                continue
            if block_size[j] > block_size[i]:
                is_strict_subset = True
                break
            if block_size[j] == block_size[i] and j < i:
                is_strict_subset = True
                break

        if not is_strict_subset:
            keep[k] = refs

    return keep


def remove_high_frequency_tokens(refDict, tokenFreqDict, max_frequency=60):
    """Drop tokens whose document frequency exceeds max_frequency.
    These act as stop-words: they appear in too many records to discriminate
    entities (e.g. state codes, generic address terms) and would inflate
    every block. Returns (cleanedRefDict, removedTokenSet).
    """
    noisy = {t for t, f in tokenFreqDict.items() if f > max_frequency}
    cleaned = {refID: [t for t in tokens if t not in noisy]
               for refID, tokens in refDict.items()}
    return cleaned, noisy


def filter_top_k_smallest(blocks, k=3, min_block_size=2):
    """Per-record top-k smallest filter (Block Filtering, Papadakis et al.).

    For each record, keep its membership only in the k smallest blocks it
    belongs to. Drop the rest. Then drop any block that ends up with
    fewer than min_block_size records (singletons aren't useful for ER).

    This reduces per-record overlap and the total candidate-pair count
    while keeping each record in its highest-precision blocks.
    """
    from collections import defaultdict

    record_to_blocks = defaultdict(list)
    for key, refs in blocks.items():
        size = len(refs)
        for refID in refs:
            record_to_blocks[refID].append((size, key))

    keep = defaultdict(set)
    for refID, sized_keys in record_to_blocks.items():
        sized_keys.sort(key=lambda x: x[0])
        for _, key in sized_keys[:k]:
            keep[key].add(refID)

    result = {}
    for key, refs in blocks.items():
        kept_ids = keep.get(key, set())
        if len(kept_ids) < min_block_size:
            continue
        result[key] = {r: refs[r] for r in refs if r in kept_ids}
    return result


class UnionFind:
    def __init__(self, elements):
        self.parent = {e: e for e in elements}
        self.rank = {e: 0 for e in elements}

    def find(self, x):
        while self.parent[x] != x:
            self.parent[x] = self.parent[self.parent[x]]  # path compression
            x = self.parent[x]
        return x

    def union(self, a, b):
        ra, rb = self.find(a), self.find(b)
        if ra == rb:
            return
        if self.rank[ra] < self.rank[rb]:
            ra, rb = rb, ra
        self.parent[rb] = ra
        if self.rank[ra] == self.rank[rb]:
            self.rank[ra] += 1

    def get_clusters(self):
        from collections import defaultdict
        clusters = defaultdict(list)
        for e in self.parent:
            clusters[self.find(e)].append(e)
        return list(clusters.values())


def build_arcs_graph(blocks):
    """Build a weighted graph using ARCS scoring.

    For each block of size s, every pair (A, B) in it gets 1/s added to its
    edge weight. This rewards co-occurrence in small (specific) blocks more
    than in large (generic) ones.

    Returns {(refID_a, refID_b): weight} with refID_a < refID_b.
    """
    from collections import defaultdict
    edge_weights = defaultdict(float)

    for refs in blocks.values():
        ref_list = list(refs.keys())
        block_size = len(ref_list)
        if block_size < 2:
            continue
        contribution = 1.0 / block_size
        for i in range(len(ref_list)):
            for j in range(i + 1, len(ref_list)):
                a, b = ref_list[i], ref_list[j]
                if a > b:
                    a, b = b, a
                edge_weights[(a, b)] += contribution

    return edge_weights


def cluster_records(blocks, all_refIDs, tau=1.0):
    """Build ARCS graph, prune edges below tau, return clusters via Union-Find."""
    print("\nBuilding ARCS weighted graph...")
    start = time.time()
    edge_weights = build_arcs_graph(blocks)
    print(f"  Graph built in {time.time() - start:.2f}s — {len(edge_weights)} edges")

    uf = UnionFind(all_refIDs)
    kept = 0
    for (a, b), w in edge_weights.items():
        if w >= tau:
            uf.union(a, b)
            kept += 1
    print(f"  Edges kept (weight >= {tau}): {kept} / {len(edge_weights)}")

    clusters = uf.get_clusters()
    multi = [c for c in clusters if len(c) > 1]
    singletons = [c for c in clusters if len(c) == 1]
    print(f"  Clusters: {len(multi)} multi-record, {len(singletons)} singletons")
    return clusters


def blocking(refDict, tokenFreqDict):
    from collections import defaultdict
    blocks = defaultdict(dict)
    avg_freq = mean(tokenFreqDict.values())
    threshold = 1.1 * avg_freq
    print("Average token frequency:", avg_freq)
    print("Token threshold:", threshold)
    
    for key in refDict:
        tokenList = refDict[key]
        for token in tokenList:
            freq = tokenFreqDict[token]
            if freq >= threshold:
                blocks[token][key] = set(tokenList)
    
    return blocks

if __name__ == "__main__":
    print("Starting...")
    refDict = build_refDict.tokenizeInput(r"C:\Users\ldfoua1\OneDrive - UA Little Rock\Documents\PhD\Blocking-only DWM\S12PX.txt")
    print(f"Loaded {len(refDict)} records")

    tokenFreqDict = build_tokenFreqDict.buildTokenFreqDict(refDict)
    print(f"Built token frequency dict with {len(tokenFreqDict)} unique tokens")

    MAX_TOKEN_FREQUENCY = 60
    refDict, removed = remove_high_frequency_tokens(refDict, tokenFreqDict,
                                                   max_frequency=MAX_TOKEN_FREQUENCY)
    print(f"Stop-word removal: dropped {len(removed)} tokens with freq > {MAX_TOKEN_FREQUENCY}")
    print(f"  Examples: {sorted(removed, key=lambda t: -tokenFreqDict[t])[:15]}")
    tokenFreqDict = build_tokenFreqDict.buildTokenFreqDict(refDict)
    print(f"Rebuilt token frequency dict: {len(tokenFreqDict)} unique tokens remain")

    stop_k = compute_stop_k(refDict)
    
    print("\nCreating initial blocks...")
    initial_blocks = blocking(refDict, tokenFreqDict)
    print(f"Initial blocks created: {len(initial_blocks)}")
    
    print("\nStarting recursive blocking...")
    final_blocks = recursive_blocking(1, initial_blocks, stop_k)

    TOP_K = 3
    print(f"\nApplying top-{TOP_K} smallest-block filter per record...")
    before = len(final_blocks)
    final_blocks = filter_top_k_smallest(final_blocks, k=TOP_K)
    print(f"  blocks: {before} -> {len(final_blocks)}")

    print(f"\n=== FINAL RESULTS ===")
    print(f"Number of final blocks: {len(final_blocks)}")

    TAU = 1.0
    print(f"\nClustering records (tau={TAU})...")
    clusters = cluster_records(final_blocks, list(refDict.keys()), tau=TAU)
    print(f"\n=== CLUSTERING RESULTS ===")
    print(f"Total clusters: {len(clusters)}")
    print(f"Multi-record clusters: {sum(1 for c in clusters if len(c) > 1)}")
    print(f"Singletons: {sum(1 for c in clusters if len(c) == 1)}")